import { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Privacy Policy - Love Language Quiz',
  description: 'Privacy Policy for Love Language Quiz. Learn how we collect, use, and protect your personal information.',
}

export default function PrivacyPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <div className="bg-white rounded-lg shadow-lg p-8 md:p-12">
        <h1 className="text-4xl font-bold mb-4 text-gray-900">Privacy Policy</h1>
        <p className="text-gray-600 mb-8">Last Updated: January 4, 2025</p>

        <div className="prose prose-lg max-w-none">
          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-900">Introduction</h2>
            <p className="text-gray-700 mb-4">
              Welcome to Love Language Quiz (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;). We respect your privacy and are committed to protecting your personal data. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website.
            </p>
            <p className="text-gray-700">
              Please read this Privacy Policy carefully. If you do not agree with the terms of this Privacy Policy, please do not access the site.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-900">Information We Collect</h2>

            <h3 className="text-xl font-semibold mb-3 text-gray-800">Automatically Collected Information</h3>
            <p className="text-gray-700 mb-4">
              When you visit our website, we automatically collect certain information about your device, including:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 space-y-2">
              <li>Browser type and version</li>
              <li>Operating system</li>
              <li>IP address (anonymized)</li>
              <li>Pages visited and time spent on pages</li>
              <li>Referring website</li>
              <li>Date and time of visit</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3 text-gray-800">Quiz Results</h3>
            <p className="text-gray-700 mb-4">
              Your quiz answers and results are stored locally in your browser using localStorage. This data:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 space-y-2">
              <li>Never leaves your device</li>
              <li>Is not transmitted to our servers</li>
              <li>Remains private to you</li>
              <li>Can be deleted by clearing your browser data</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3 text-gray-800">Information You Provide</h3>
            <p className="text-gray-700 mb-4">
              We do not require you to create an account or provide personal information to use our quiz. Any information you choose to share through the &quot;Share Results&quot; or &quot;Invite Others&quot; features is processed locally on your device.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-900">How We Use Your Information</h2>
            <p className="text-gray-700 mb-4">
              We use the automatically collected information to:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 space-y-2">
              <li>Improve and optimize our website</li>
              <li>Understand how users interact with our content</li>
              <li>Analyze website traffic and usage patterns</li>
              <li>Detect and prevent technical issues</li>
              <li>Enhance user experience</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-900">Google Analytics</h2>
            <p className="text-gray-700 mb-4">
              We use Google Analytics to help us understand how visitors use our website. Google Analytics collects information anonymously and reports website trends without identifying individual visitors.
            </p>
            <p className="text-gray-700 mb-4">
              Google Analytics uses cookies to collect data. The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States.
            </p>
            <p className="text-gray-700 mb-4">
              You can opt-out of Google Analytics by installing the{' '}
              <a
                href="https://tools.google.com/dlpage/gaoptout"
                target="_blank"
                rel="noopener noreferrer"
                className="text-rose-600 hover:text-rose-700 underline"
              >
                Google Analytics Opt-out Browser Add-on
              </a>.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-900">Cookies</h2>
            <p className="text-gray-700 mb-4">
              We use cookies and similar tracking technologies to track activity on our website and store certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier.
            </p>
            <p className="text-gray-700 mb-4">
              You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our website.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-900">Data Storage and Security</h2>
            <p className="text-gray-700 mb-4">
              Your quiz results are stored locally in your browser using localStorage technology. This means:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 space-y-2">
              <li>Your data never leaves your device</li>
              <li>We cannot access your quiz results</li>
              <li>Your data is as secure as your device</li>
              <li>Clearing your browser data will delete your results</li>
            </ul>
            <p className="text-gray-700">
              While we strive to use commercially acceptable means to protect any data we process, no method of transmission over the Internet or method of electronic storage is 100% secure.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-900">Third-Party Links</h2>
            <p className="text-gray-700">
              Our website may contain links to third-party websites. We are not responsible for the privacy practices or content of these third-party sites. We encourage you to read the privacy policies of any third-party sites you visit.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-900">Children&apos;s Privacy</h2>
            <p className="text-gray-700">
              Our website is not intended for children under the age of 13. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and believe your child has provided us with personal information, please contact us.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-900">Your Rights</h2>
            <p className="text-gray-700 mb-4">
              Depending on your location, you may have certain rights regarding your personal information, including:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 space-y-2">
              <li>The right to access your personal data</li>
              <li>The right to rectification of inaccurate data</li>
              <li>The right to erasure of your data</li>
              <li>The right to restrict processing</li>
              <li>The right to data portability</li>
              <li>The right to object to processing</li>
            </ul>
            <p className="text-gray-700">
              Since we do not collect or store your quiz results on our servers, you have complete control over your data through your browser settings.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-900">GDPR Compliance (EU Users)</h2>
            <p className="text-gray-700 mb-4">
              If you are a resident of the European Economic Area (EEA), you have certain data protection rights under the General Data Protection Regulation (GDPR).
            </p>
            <p className="text-gray-700 mb-4">
              The legal basis for processing your data through Google Analytics is our legitimate interest in understanding how our website is used and improving our services.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-900">CCPA Compliance (California Users)</h2>
            <p className="text-gray-700 mb-4">
              If you are a California resident, you have specific rights under the California Consumer Privacy Act (CCPA), including the right to:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 space-y-2">
              <li>Know what personal information is collected</li>
              <li>Know if your personal information is sold or disclosed</li>
              <li>Say no to the sale of personal information</li>
              <li>Access your personal information</li>
              <li>Request deletion of your personal information</li>
              <li>Equal service and price</li>
            </ul>
            <p className="text-gray-700">
              We do not sell your personal information.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-900">Changes to This Privacy Policy</h2>
            <p className="text-gray-700 mb-4">
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the &quot;Last Updated&quot; date at the top of this policy.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4 text-gray-900">Contact Us</h2>
            <p className="text-gray-700 mb-4">
              If you have any questions about this Privacy Policy, please contact us through our GitHub repository or by visiting our website.
            </p>
          </section>

          <div className="mt-12 p-6 bg-blue-50 rounded-lg border-2 border-blue-200">
            <h3 className="text-lg font-semibold mb-2 text-blue-900">Summary</h3>
            <p className="text-blue-800">
              Your privacy matters to us. We use minimal tracking (Google Analytics) to improve our website, and your quiz results stay private on your device. We never sell your data or require personal information to use our quiz.
            </p>
          </div>

          <div className="mt-8 text-center">
            <Link
              href="/"
              className="inline-block bg-rose-600 text-white px-8 py-3 rounded-lg font-semibold hover:bg-rose-700 transition-colors"
            >
              Back to Home
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}
